### ISSUE TITLE
Refactoring into a different class

### ISSUE THREAD

**Issue by kyhjonathan** [nus-cs2113-AY2324S2/forum#10]
Hi! After Friday's lecture I had a question regarding refactoring. Is there a way in refactoring a method into a different class rather than it being placed at the bottom of the class that was refactored from? (e.g. I refactored a method from main and its put into the bottom of main, but I want the method to be automatically placed in another class called Tasks)

**Comment by okkhoy** [comment]
See if [this](https://www.jetbrains.com/help/idea/move-refactorings.html) helps?
