### ISSUE TITLE
Compiling multiple packages within runtest.bat

### ISSUE THREAD

**Issue by clarencepohh** [nus-cs2113-AY2324S2/forum#13]
From the lecture, it was shown that we can compile files from different packages when conducting text-ui testing by individually including the package path inside the runtest.bat or runtest.sh. Can we use build tools such as Ant or Maven to assist in compilation, especially since we expect to abstract more files into packages in the future? 

Thanks in advance 😄

**Comment by okkhoy** [comment]
We will use Gradle later in the course; feel free to incorporate it if necessary now!
Just ensure that the JAR you generate works well on any machine that runs Java 11.

**Comment by clarencepohh** [comment]
Understood :) thanks for your help!
