### ISSUE TITLE
Coursemology Exercise Froze

### ISSUE THREAD

**Issue by adamzzq** [nus-cs2113-AY2324S2/forum#19]
Hi prof,

I submitted week 6's exercises on coursemology, which passed all test cases when I tested them before submission, however, when I finalise the submission the grades didn't show up as usual. There seems to be some issue with the auto-grader.
Could you help me check it from the course instructor's side?
Thank you.

As shown, it has been evaluating the answer since 30min ago:
![image](https://github.com/nus-cs2113-AY2324S2/forum/assets/110774216/10fda8ef-8369-4f82-b0ac-ab3affb9a7d2)

**Comment by okkhoy** [comment]
@sevenseasofbri can you pls help to take a look?

**Comment by sevenseasofbri** [comment]
@okkhoy @adamzzq seems ok on our end:

Edit: removed screenshot!

**Comment by okkhoy** [comment]
Thanks, @sevenseasofbri

**Comment by adamzzq** [comment]
Thank you, it shows correctly now
