### ISSUE TITLE
Automated Text UI Testing - input.txt is blank?

### ISSUE THREAD

**Issue by LWachtel1** [nus-cs2113-AY2324S2/forum#20]
For the optional Week 4 IP milestone, A-TextUiTesting, my input.txt file is blank i.e., it has no example inputs for me to run to check my chatbot's functionality.

Is this is an error that has occurred due to an incorrect fork-and-clone OR are we meant to populate input.txt with our own test inputs?

**Comment by e0958902** [comment]
What I did on my end is to manually populate the input.txt with the commands I want to test that is relevant to my program.
e.g "todo read book" then "list". Perhaps someone else could verify if they did the same too?

**Comment by BenjoBurger** [comment]
I did the same too. You can refer to other's input.txt file if you need some reference!

**Comment by okkhoy** [comment]
`input.txt` is testing your product; so you need to populate it yourself.
