### ISSUE TITLE
Is it ok to tag buggy commit?

### ISSUE THREAD

**Issue by awesomesjh** [nus-cs2113-AY2324S2/forum#24]
For week 7 iP we were given instructions to "tag the merge commit in the master branch". However, I realized later on that my commits had a bug that would throw an error if a deadline is stored in the storage file when reading the file initially. I have since resolved the error, but I am wondering if I should tag the latest commit instead?

**Comment by okkhoy** [comment]
ideally, you should branch out the relevant branch, code the fix and merge back to master again, and tag the merge with the fix.

**Comment by awesomesjh** [comment]
The buggy branch was branch-Level-8, however I have already pushed it to the fork, pulled it to master and merged with branch-Level-9 and branch-A-JavaDoc, causing both branches to contain the bug as well. Furthermore, I have already committed the fix to the master branch. May I know how I can resolve this?

**Comment by okkhoy** [comment]
@awesomesjh I have tried to understand the situation and explain things here: 

https://www.loom.com/share/6a44111d72234ff1b1f320d4b1f25796?sid=45d4e832-7539-43ef-ad03-ecea8fa7937e

Let me know if it helps

**Comment by awesomesjh** [comment]
Thanks for the video prof! I have carried out the cherry-picking and merging as you mentioned.
