### ISSUE TITLE
Question about the grading of comments of ip.

### ISSUE THREAD

**Issue by runxinghuan** [nus-cs2113-AY2324S2/forum#25]
On the website, it says "At least half of public methods/classes have javadoc comments." For self-explanatory methods, I think we do not need to add a comment. I want to ask that when counting the number of comments, will these self-explanatory methods be counted as having javadoc comments?

**Comment by okkhoy** [comment]
As a rule of thumb, as long as it is not a getter/setter, add javadoc comments.
