### ISSUE TITLE
Question for ip commit

### ISSUE THREAD

**Issue by runxinghuan** [nus-cs2113-AY2324S2/forum#3]
The website says "Minimally, commit after completing each increment." I want to ask that do we create a local repo, then commit it. Or we push to the forked repo on Github?

**Comment by okkhoy** [comment]
Hmm.. you need to do both. 
You commit locally and push the commits to the GitHub forked repo. Our checks will happen on Git Hub.

**Comment by runxinghuan** [comment]
Noted with thanks!
