### ISSUE TITLE
Question on Week3-Coding Assessment Exercise 10

### ISSUE THREAD

**Issue by HenryGan138** [nus-cs2113-AY2324S2/forum#4]
After multiple try, my running code cannot match the expected output on the test compiler, while there is no problem on my local compiler. I am wondering if there is any mistake on the test input.
Thank you for your assistance.
<img width="878" alt="屏幕截图 2024-01-27 230956" src="https://github.com/nus-cs2113-AY2324S2/forum/assets/86831302/7cafc4ce-bfa5-44c7-93bd-d7ec69d581bb">

**Comment by STeng618** [comment]
Try importing all the libraries used in your code?

**Comment by JianJiaT** [comment]
I had the same issue, but it turned out to be me adding an unnecessary space after the colon

**Comment by HenryGan138** [comment]
Thanks, both of your solutions are helpful.
After I importing the libraries, and changing system.out.println() into system.out.print(), it works successfully.
