### ISSUE TITLE
Questions regarding Association and Navigability

### ISSUE THREAD

**Issue by ZMinghuiZ** [nus-cs2113-AY2324S2/forum#48]
1. Does anyone know that the association line with no directed arrow means no navigability between the linked classes or the navigabilities are not specified?
<img width="656" alt="image" src="https://github.com/nus-cs2113-AY2324S2/forum/assets/110764547/e628263f-d12e-493c-8e40-dd78285dd819">

2. Is there any code examples of two classes that linked with association but they do not have navigability of each other?
<img width="1106" alt="image" src="https://github.com/nus-cs2113-AY2324S2/forum/assets/110764547/7ddff498-c77a-48ca-997d-bc0f21c46ba0">

Thank you.

**Comment by okkhoy** [comment]
No arrows mean you don't know (not specified).
You encounter this situation in the design phase.
Once you have the code, you know which class holds the reference of the other (i.e., navigability).

**Comment by ZMinghuiZ** [comment]
Okay, thank you Prof!
