### ISSUE TITLE
Mock final exam question 7 answer clarification

### ISSUE THREAD

**Issue by adamzzq** [nus-cs2113-AY2324S2/forum#49]
Hi prof,
![image](https://github.com/nus-cs2113-AY2324S2/forum/assets/110774216/430f15c1-ef95-4b78-84fd-3264f3aef218)
In line 10, why is the coding standard violation not "indentation is 6 spaces instead of 8"?
Is it understood as the indentation relative to the previous line is 2 spaces instead of 4?
Which way of describing is preferred in the exam?

Thank you

**Comment by okkhoy** [comment]
> Is it understood as the indentation relative to the previous line is 2 spaces instead of 4?

yes.

you write either, I am OK! 🙂
