### ISSUE TITLE
Local Commits on New Branch

### ISSUE THREAD

**Issue by JianJiaT** [nus-cs2113-AY2324S2/forum#5]
![image](https://github.com/nus-cs2113-AY2324S2/forum/assets/110650168/2822df77-bd33-4996-b6a3-1b7d5af8e7b0)

I received an error when attempting to push my local code to my GitHub repo ("Updates were rejected because the tip of your current branch is behind its remote counterpart"), and when I fetched from the GitHub repo it appears that my local commits are on a new, different branch from my GitHub repo. I tried to checkout at origin/master and merging my first local commit, but it failed as they were unrelated histories. How did this issue arise, and how would I fix this issue?

**Comment by okkhoy** [comment]
Not sure how you ended up in this state. Can you give the screenshot of SourceTree commit history with all branches shown?

**Comment by JianJiaT** [comment]
![image](https://github.com/nus-cs2113-AY2324S2/forum/assets/110650168/664c4247-ad0a-4cae-86f6-083532c38c2f)
Not sure how to make the commit history bigger, but I can scroll down all the way to find the initial commit of the remote branch

**Comment by okkhoy** [comment]
Sorry, can't make much sense. Please ping me on MSTeams to continue the triaging.

**Comment by JianJiaT** [comment]
Solved with the help of prof, turns out I cloned to the wrong folder
