### ISSUE TITLE
Inheritance vs Association?

### ISSUE THREAD

**Issue by JackieNeoCEG** [nus-cs2113-AY2324S2/forum#50]
Hi!

Can I check if Inheritance is a "special" form of association? I understand that they are catagorised between "is-a" relation and "has-a" relation but I don't know if they have something in common. E.g Suppose Child Class Circle inherited from Parent Class Shape, can I also draw an association pointing from circle to shape in the object diagram?

**Comment by okkhoy** [comment]
In lay terms,
Inheritance is "getting things/behaviors from parent class"
Association is maintaining reference of one in another. 

WRT your example, nothing prevents you from having an association from circle to shape.

**Comment by JackieNeoCEG** [comment]
Thank you Prof!
