### ISSUE TITLE
Customizing the chatbot

### ISSUE THREAD

**Issue by adamzzq** [nus-cs2113-AY2324S2/forum#6]
Hi prof Akshay!
I'd like to clarify some ip specifications.
I understand that we are encouraged to customize the command/display formats. Does this mean that we can name the commands differently? e.g. instead of `bye` for exiting the app, can I use `exit`? And can I allow the user to use multiple keywords to perform the same action? e.g. both `bye` and `exit` will terminate the app.

Moreover, does "customizing the personality of the chatbot" just mean changing the given prompts shown in the ip examples? 
Are we allowed to add new features, or even alter the given mechanism? e.g. I'm thinking of adding an extra confirmation step for some commands.

**Comment by okkhoy** [comment]
As long as you maintain the basic functionality to be that of a task manager, you are free to customize it in any way you would like.
If you are changing the command words, be sure to document the new commands. 
In general, try to adhere to the [constraints that we specify for the tP](https://nus-cs2113-ay2324s2.github.io/website/admin/tp-constraints.html#tp-constraints) in the iP as well.

**Comment by adamzzq** [comment]
I see, thank you prof Akshay
