### ISSUE TITLE
SourceTree Graph differs from what it is supposed to look like 

### ISSUE THREAD

**Issue by Daviancold** [nus-cs2113-AY2324S2/forum#7]
Hi there! Recently I discovered that my graph does not look the way it is supposed to be. For reference, the graph is supposed to show a branch at ".gitignore Fix ACTUAL.txt" as shown below.
![image_2024-02-01_19-03-55](https://github.com/nus-cs2113-AY2324S2/forum/assets/110613918/63b60e29-b705-4f92-be08-6b0c50783ad0)

However, my own graph shows that it does not have a branch, instead the entire branch is on main.
![image](https://github.com/nus-cs2113-AY2324S2/forum/assets/110613918/51f4421c-13d5-44fa-b908-c40932e10bff)

I would like to ask, is there any ramifications in it being different? My GitHub repository still shows that I have the "Add Gradle Support" Branch.

**Comment by okkhoy** [comment]
Have you cloned within a clone? That could lead to mess like this. 
But TBH, I am not sure what led to this kind of linear commit tree!

**Comment by Daviancold** [comment]
I did not clone within a clone. Would this affect the auto-grading script for my submissions?

**Comment by okkhoy** [comment]
Not sure, since this is the first time I am seeing this issue.
Check if you have all reds in the [dashboard](https://nus-cs2113-ay2324s2.github.io/dashboards/contents/ip-progress.html)? If so, we need to find a way to fix it. If not, things should be fine :-)

**Comment by Daviancold** [comment]
The dashboard seems fine! Thanks for the help, I think I will stick to the current graph that I have at the moment.
